# list with all available versions of node.js images
# https://github.com/CircleCI-Public/circleci-dockerfiles/tree/master/node/images
version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  install:
    executor: node/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - c00k-b00k-{{ .Branch }}-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - c00k-b00k-
      - run:
          name: Installing dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          key: c00k-b00k-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - ~/.cache
      - store_artifacts:
          path: yarn-error.log
      - persist_to_workspace:
          root: .
          paths:
            - node_modules

  lint:
    executor: node/default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Linting library
          command: yarn lint

  test:
    executor: node/default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Running test suits
          command: yarn test

  build:
    executor: node/default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Building the library
          command: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - lib
      - store_artifacts:
          path: lib

  release:
    executor: node/default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - add_ssh_keys:
          fingerprints:
            - $GITHUB_FINGERPRINT
      - run:
          name: Set git upstream
          command: git branch --set-upstream-to origin/${CIRCLE_BRANCH}
      - run:
          name: Running semantic-release workflow
          command: npx semantic-release
      - store_artifacts:
          path: release

workflows:
  version: 2
  'Test, Build & Maybe Deploy':
    jobs:
      - install
      - lint:
          requires:
            - install
      - test:
          requires:
            - install
      - build:
          requires:
            - lint
      - release:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - next
                - pre/rc
                - beta
